In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("bank-additional-full.csv", sep=";")

In [3]:
df.shape

(41188, 21)

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  duration  campaign  pdays  previous     poutcome  \
0   may         mon       261         1    999         0  nonexistent   
1   may         mon       149         1    999         0  nonexistent   
2   may         mon       226         1    999         0  nonexistent   
3   may         mon       151         1    999         0  nonexistent   
4   may         mon       307         1    999         0  nonexistent   

   emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0           1.1          93.994          -36.4      4.857       5191.0  no  
1           1.1          93.994          -36.4      4.857       5191.0  no  
2           1.1          93.994          -36.4      4.857       5191.0  no  
3           1.1          93.994          -36.4      4.857       5191.0  no  
4           1.1          93.994          -36.4      4.857       5191.0  no

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [7]:
df[df == "unknown"].count()

age                  0
job                330
marital             80
education         1731
default           8597
housing            990
loan               990
contact              0
month                0
day_of_week          0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx       0
cons.conf.idx        0
euribor3m            0
nr.employed          0
y                    0
dtype: int64

In [8]:
df = df[~(df['job']=="unknown")]

In [9]:
df = df[~(df['marital']=="unknown")]

In [10]:
df = df[~(df['education']=="unknown")]

In [11]:
df = df[~(df['default']=="unknown")]

In [12]:
df = df[~(df['housing']=="unknown")]

In [13]:
df = df[~(df['loan']=="unknown")]

In [14]:
df.shape

(30488, 21)

In [15]:
df["y"] = df["y"].map({"yes":1, "no":0})
df.head()

age        job  marital            education default housing loan  \
0   56  housemaid  married             basic.4y      no      no   no   
2   37   services  married          high.school      no     yes   no   
3   40     admin.  married             basic.6y      no      no   no   
4   56   services  married          high.school      no      no  yes   
6   59     admin.  married  professional.course      no      no   no   

     contact month day_of_week  duration  campaign  pdays  previous  \
0  telephone   may         mon       261         1    999         0   
2  telephone   may         mon       226         1    999         0   
3  telephone   may         mon       151         1    999         0   
4  telephone   may         mon       307         1    999         0   
6  telephone   may         mon       139         1    999         0   

      poutcome  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0  nonexistent           1.1          93.994          -36.4      4.857   
2  nonexistent           1.1          93.994          -36.4      4.857   
3  nonexistent           1.1          93.994          -36.4      4.857   
4  nonexistent           1.1          93.994          -36.4      4.857   
6  nonexistent           1.1          93.994          -36.4      4.857   

   nr.employed  y  
0       5191.0  0  
2       5191.0  0  
3       5191.0  0  
4       5191.0  0  
6       5191.0  0

In [16]:
df[df["y"]==1]

age          job  marital            education default housing loan  \
88      49   technician  married             basic.9y      no      no   no   
182     42  blue-collar  married             basic.9y      no     yes  yes   
286     39    housemaid  married             basic.9y      no     yes   no   
389     44     services  married          high.school      no     yes   no   
446     42   technician  married  professional.course      no      no   no   
...    ...          ...      ...                  ...     ...     ...  ...   
41174   62      retired  married    university.degree      no     yes   no   
41178   62      retired  married    university.degree      no      no   no   
41181   37       admin.  married    university.degree      no     yes   no   
41183   73      retired  married  professional.course      no     yes   no   
41186   44   technician  married  professional.course      no      no   no   

         contact month day_of_week  duration  campaign  pdays  previous  \
88     telephone   may         mon      1467         1    999         0   
182    telephone   may         mon       673         2    999         0   
286    telephone   may         mon       935         3    999         0   
389    telephone   may         tue      1030         1    999         0   
446    telephone   may         tue      1623         1    999         0   
...          ...   ...         ...       ...       ...    ...       ...   
41174   cellular   nov         thu       208         1      1         6   
41178   cellular   nov         thu       483         2      6         3   
41181   cellular   nov         fri       281         1    999         0   
41183   cellular   nov         fri       334         1    999         0   
41186   cellular   nov         fri       442         1    999         0   

          poutcome  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
88     nonexistent           1.1          93.994          -36.4      4.857   
182    nonexistent           1.1          93.994          -36.4      4.857   
286    nonexistent           1.1          93.994          -36.4      4.857   
389    nonexistent           1.1          93.994          -36.4      4.857   
446    nonexistent           1.1          93.994          -36.4      4.857   
...            ...           ...             ...            ...        ...   
41174      success          -1.1          94.767          -50.8      1.031   
41178      success          -1.1          94.767          -50.8      1.031   
41181  nonexistent          -1.1          94.767          -50.8      1.028   
41183  nonexistent          -1.1          94.767          -50.8      1.028   
41186  nonexistent          -1.1          94.767          -50.8      1.028   

       nr.employed  y  
88          5191.0  1  
182         5191.0  1  
286         5191.0  1  
389         5191.0  1  
446         5191.0  1  
...            ... ..  
41174       4963.6  1  
41178       4963.6  1  
41181       4963.6  1  
41183       4963.6  1  
41186       4963.6  1  

[3859 rows x 21 columns]

In [17]:
categorical_col = list(df.dtypes[df.dtypes == 'object'].index)
categorical_col

['job',
 'marital',
 'education',
 'default',
 'housing',
 'loan',
 'contact',
 'month',
 'day_of_week',
 'poutcome']

In [18]:
numerical_col = list(df.dtypes[df.dtypes != 'object'].index)
numerical_col.remove("y")
numerical_col

['age',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'emp.var.rate',
 'cons.price.idx',
 'cons.conf.idx',
 'euribor3m',
 'nr.employed']

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [21]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [22]:
total_term_deposit = df_full_train.y.mean()
total_term_deposit

0.12566625666256662

In [23]:
for c in categorical_col:
    print(c)
    df_group = df_full_train.groupby(c).y.agg(['mean', 'count'])
    df_group['diff'] = df_group['mean'] - total_term_deposit
    df_group['risk'] = df_group['mean'] / total_term_deposit
    display(df_group)
    print()
    print()

job


mean  count      diff      risk
job                                               
admin.         0.143165   6957  0.017499  1.139249
blue-collar    0.077346   4551 -0.048321  0.615485
entrepreneur   0.088681    857 -0.036985  0.705690
housemaid      0.125000    544 -0.000666  0.994698
management     0.119112   1847 -0.006554  0.947845
retired        0.287000   1000  0.161334  2.283827
self-employed  0.124714    874 -0.000952  0.992422
services       0.089559   2289 -0.036107  0.712671
student        0.334029    479  0.208363  2.658066
technician     0.111263   4386 -0.014403  0.885386
unemployed     0.171617    606  0.045951  1.365658



marital


mean  count      diff      risk
marital                                      
divorced  0.113604   2852 -0.012062  0.904017
married   0.115920  14001 -0.009746  0.922446
single    0.148335   7537  0.022669  1.180388



education


mean  count      diff      risk
education                                               
basic.4y             0.131811   1927  0.006145  1.048898
basic.6y             0.092793   1110 -0.032873  0.738407
basic.9y             0.087889   3402 -0.037777  0.699388
high.school          0.123107   6141 -0.002559  0.979634
illiterate           0.333333      6  0.207667  2.652529
professional.course  0.118669   3455 -0.006998  0.944316
university.degree    0.148641   8349  0.022974  1.182820



default


mean  count      diff      risk
default                                     
no       0.125677  24388  0.000010  1.000082
yes      0.000000      2 -0.125666  0.000000



housing


mean  count      diff      risk
housing                                     
no       0.122402  11209 -0.003265  0.974022
yes      0.128442  13181  0.002776  1.022092



loan


mean  count      diff      risk
loan                                     
no    0.125596  20542 -0.000070  0.999444
yes   0.126040   3848  0.000373  1.002970



contact


mean  count      diff      risk
contact                                       
cellular   0.158780  16356  0.033113  1.263503
telephone  0.058252   8034 -0.067414  0.463549



month


mean  count      diff      risk
month                                     
apr    0.223199   1707  0.097532  1.776122
aug    0.114622   3734 -0.011044  0.912117
dec    0.434426    122  0.308760  3.456984
jul    0.096331   4007 -0.029335  0.766566
jun    0.121733   2908 -0.003933  0.968702
mar    0.510363    386  0.384696  4.061255
may    0.071263   7774 -0.054403  0.567083
nov    0.103924   2829 -0.021743  0.826981
oct    0.448544    515  0.322877  3.569325
sep    0.458333    408  0.332667  3.647227



day_of_week


mean  count      diff      risk
day_of_week                                     
fri          0.117544   4577 -0.008122  0.935368
mon          0.112935   5056 -0.012731  0.898691
thu          0.135907   5077  0.010241  1.081492
tue          0.130816   4793  0.005150  1.040978
wed          0.130755   4887  0.005089  1.040495



poutcome


mean  count      diff      risk
poutcome                                        
failure      0.146228   2797  0.020562  1.163623
nonexistent  0.097978  20627 -0.027688  0.779671
success      0.657350    966  0.531684  5.230918

In [24]:
y_train = df_train.y
y_val = df_val.y
y_test = df_test.y

In [25]:
del df_train["y"]
del df_val["y"]
del df_test["y"]

### Feature importance: Mutual Information

In [26]:
from sklearn.metrics import mutual_info_score

In [27]:
def mutual_info_churn_score(series):
    return mutual_info_score(series, df_full_train.y)

In [28]:
mi = df_full_train[categorical_col].apply(mutual_info_churn_score)
mi.sort_values(ascending=False)

poutcome       3.373602e-02
month          2.913468e-02
contact        1.141199e-02
job            1.050638e-02
education      2.112870e-03
marital        1.022016e-03
day_of_week    3.588838e-04
housing        4.129292e-05
default        1.101263e-05
loan           1.186736e-07
dtype: float64

### Feature importance: Correlation

In [29]:
df_full_train[numerical_col].corrwith(df_full_train.y).abs().sort_values(ascending=False)

duration          0.391287
nr.employed       0.366789
pdays             0.332864
euribor3m         0.317713
emp.var.rate      0.305990
previous          0.229061
cons.price.idx    0.128586
campaign          0.068158
cons.conf.idx     0.066200
age               0.047813
dtype: float64

### One hot encoding

In [30]:
from sklearn.feature_extraction import DictVectorizer

In [31]:
dv = DictVectorizer(sparse=False)

train_dict = df_train.to_dict(orient="records")
X_train = dv.fit_transform(train_dict)

val_dict = df_val.to_dict(orient="records")
X_val = dv.transform(val_dict)

### Full data model training

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [34]:
model.intercept_[0]

0.0027896788679440234

In [35]:
model.coef_[0].round(3)

array([ 0.006, -0.059,  0.043,  0.219,  0.043, -0.041, -0.003, -0.007,
        0.002,  0.005,  0.005,  0.003, -0.   ,  0.005, -0.005, -0.003,
       -0.012, -0.   ,  0.   ,  0.002,  0.02 , -0.267, -0.287, -0.005,
        0.008,  0.017, -0.026, -0.003, -0.001, -0.002,  0.01 ,  0.002,
       -0.007,  0.01 ,  0.002,  0.001,  0.001,  0.002, -0.004, -0.015,
        0.022,  0.015,  0.004,  0.001, -0.003,  0.009,  0.021, -0.055,
       -0.008,  0.013,  0.007, -0.004, -0.002, -0.002, -0.001,  0.006,
        0.007])

In [36]:
y_pred = model.predict_proba(X_val)[:,1]

In [37]:
y_pred

array([0.02007904, 0.05697468, 0.00574761, ..., 0.14290977, 0.02185254,
       0.01272071])

In [38]:
y_class = y_pred >= 0.6
y_class

array([False, False, False, ..., False, False, False])

In [39]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

In [40]:
accuracy_score(y_val, y_class)

0.8993112495900295

In [41]:
np.sqrt(mean_squared_error(y_val,y_class))

0.3173149073238925

### After feature selection model

In [42]:
top_cat_col = ["poutcome", "month", "contact", "job", "education"]

In [43]:
top_num_col = ["duration", "nr.employed", "pdays", "euribor3m", "emp.var.rate"]

In [44]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[top_cat_col + top_num_col].to_dict(orient="records")
X_train_f = dv.fit_transform(train_dict)

val_dict = df_val[top_cat_col + top_num_col].to_dict(orient="records")
X_val_f = dv.transform(val_dict)

In [45]:
model_f = LogisticRegression(solver='lbfgs', C=1.0, random_state=42)
model_f.fit(X_train_f, y_train)

LogisticRegression(random_state=42)

In [46]:
y_pred_f = model_f.predict_proba(X_val_f)[:,1]
y_class_f = y_pred_f >= 0.6
y_class_f

array([False, False, False, ..., False, False, False])

In [47]:
accuracy_score(y_val, y_class_f)

0.8948835683830764

### Random Forest

In [48]:
from sklearn.ensemble import RandomForestRegressor

In [49]:
rf = RandomForestRegressor(n_estimators=10, random_state=1, n_jobs=-1)
rf.fit(X_train_f, y_train)

RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=1)

In [50]:
y_pred_rf = rf.predict(X_val_f)
y_pred_rf

array([0., 0., 0., ..., 0., 0., 0.])

In [51]:
from sklearn.metrics import mean_squared_error

In [52]:
np.sqrt(mean_squared_error(y_val,y_pred_rf))

0.2707116112519298

In [53]:
y_pred_rf

array([0., 0., 0., ..., 0., 0., 0.])

In [54]:
score = []
for est in range(10,201,10):
    rf = RandomForestRegressor(n_estimators=est, random_state=1, n_jobs=-1)
    rf.fit(X_train_f, y_train)
    
    y_pred_rf = rf.predict(X_val_f)
    score.append(np.sqrt(mean_squared_error(y_val,y_pred_rf)))
    print("est : %4s , rmse : %.3f" % (est, np.sqrt(mean_squared_error(y_val,y_pred_rf))))

est :   10 , rmse : 0.271
est :   20 , rmse : 0.265
est :   30 , rmse : 0.264
est :   40 , rmse : 0.264
est :   50 , rmse : 0.263
est :   60 , rmse : 0.263
est :   70 , rmse : 0.263
est :   80 , rmse : 0.262
est :   90 , rmse : 0.262
est :  100 , rmse : 0.262
est :  110 , rmse : 0.262
est :  120 , rmse : 0.263
est :  130 , rmse : 0.262
est :  140 , rmse : 0.262
est :  150 , rmse : 0.262
est :  160 , rmse : 0.262
est :  170 , rmse : 0.262
est :  180 , rmse : 0.262
est :  190 , rmse : 0.262
est :  200 , rmse : 0.262


In [55]:
score = []
for max_depth in (10, 15, 20, 25):
    print("Max Depth: %d" % max_depth)
    for est in range(10,201,10):
        rf = RandomForestRegressor(n_estimators=est, random_state=1, n_jobs=-1)
        rf.fit(X_train_f, y_train)

        y_pred_rf = rf.predict(X_val_f)
        score.append(np.sqrt(mean_squared_error(y_val,y_pred_rf)))
        print("est : %4s , rmse : %.3f" % (est, np.sqrt(mean_squared_error(y_val,y_pred_rf))))

Max Depth: 10
est :   10 , rmse : 0.271
est :   20 , rmse : 0.265
est :   30 , rmse : 0.264
est :   40 , rmse : 0.264
est :   50 , rmse : 0.263
est :   60 , rmse : 0.263
est :   70 , rmse : 0.263
est :   80 , rmse : 0.262
est :   90 , rmse : 0.262
est :  100 , rmse : 0.262
est :  110 , rmse : 0.262
est :  120 , rmse : 0.263
est :  130 , rmse : 0.262
est :  140 , rmse : 0.262
est :  150 , rmse : 0.262
est :  160 , rmse : 0.262
est :  170 , rmse : 0.262
est :  180 , rmse : 0.262
est :  190 , rmse : 0.262
est :  200 , rmse : 0.262
Max Depth: 15
est :   10 , rmse : 0.271
est :   20 , rmse : 0.265
est :   30 , rmse : 0.264
est :   40 , rmse : 0.264
est :   50 , rmse : 0.263
est :   60 , rmse : 0.263
est :   70 , rmse : 0.263
est :   80 , rmse : 0.262
est :   90 , rmse : 0.262
est :  100 , rmse : 0.262
est :  110 , rmse : 0.262
est :  120 , rmse : 0.263
est :  130 , rmse : 0.262
est :  140 , rmse : 0.262
est :  150 , rmse : 0.262
est :  160 , rmse : 0.262
est :  170 , rmse : 0.262
est :  180

### Cross Validation

In [56]:
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score

In [57]:
def train(df_train, y_train, C=1.0):
    dicts = df_train[top_cat_col + top_num_col].to_dict(orient='records')

    dv = DictVectorizer(sparse=False)
    X_train = dv.fit_transform(dicts)

    model = LogisticRegression(C=C, max_iter=1000)
    model.fit(X_train, y_train)
    
    return dv, model

In [58]:
def predict(df, dv, model):
    dicts = df[top_cat_col + top_num_col].to_dict(orient='records')

    X = dv.transform(dicts)
    y_pred = model.predict_proba(X)[:, 1]

    return y_pred

In [59]:
C=1.0
n_splits = 10
kfold = KFold(n_splits=n_splits, shuffle=True, random_state=1)

scores = []

for train_idx, val_idx in kfold.split(df_full_train):
    df_train = df_full_train.iloc[train_idx]
    df_val = df_full_train.iloc[val_idx]

    y_train = df_train.y.values
    y_val = df_val.y.values

    dv, model = train(df_train, y_train, C=C)
    y_pred = predict(df_val, dv, model)

    auc = roc_auc_score(y_val, y_pred)
    scores.append(auc)

print('C=%s %.3f +- %.3f' % (C, np.mean(scores), np.std(scores)))

C=1.0 0.924 +- 0.006


In [60]:
scores

[0.9334654005374615,
 0.9223530637446415,
 0.9205212256002138,
 0.9243912379011716,
 0.9280055925146342,
 0.9177436233456006,
 0.9152129089055694,
 0.9333338681985205,
 0.9170179856454367,
 0.9306445660371303]

In [61]:
dv, model = train(df_full_train, df_full_train.y.values, C=1.0)
y_pred = predict(df_test, dv, model)

auc = roc_auc_score(y_test, y_pred)
auc

0.9193080836287236

### Save the model

In [62]:
import pickle

In [63]:
output_file = f'model_C={C}.bin'

In [64]:
with open(output_file, 'wb') as f_out: 
    pickle.dump((dv, model), f_out)

### Load the model

In [1]:
import pickle

In [2]:
input_file = 'model_C=1.0.bin'

In [3]:
with open(input_file, 'rb') as f_in: 
    dv, model = pickle.load(f_in)

In [4]:
model

LogisticRegression(max_iter=1000)

In [5]:
customer = {
    'poutcome':'success',
    'month':'nov',
    'contact':'cellular',
    'job':'retired',
    'education':'university.degree',
    'duration':208,
    'nr.employed':4963.6,
    'pdays':1,
    'euribor3m':1.031,
    'emp.var.rate':-1.1
}

In [6]:
X = dv.transform([customer])

In [7]:
y_pred = model.predict_proba(X)[0, 1]

In [8]:
print('input:', customer)
print('output:', y_pred)

input: {'poutcome': 'success', 'month': 'nov', 'contact': 'cellular', 'job': 'retired', 'education': 'university.degree', 'duration': 208, 'nr.employed': 4963.6, 'pdays': 1, 'euribor3m': 1.031, 'emp.var.rate': -1.1}
output: 0.5766161410665501
