##### Question 1.) What's the version of NumPy that you installed?

In [2]:
import numpy as np
np.__version__

'1.20.1'

##### Question 2.) What's the version of Pandas?

In [5]:
import pandas as pd
pd.__version__

'1.2.4'

##### Question 3.) What's the average price of BMW cars in the dataset?

In [7]:
df = pd.read_csv("data.csv")
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [12]:
df[df.Make == "BMW"]["MSRP"].mean()

61546.76347305389

##### Question 4.) Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [14]:
df[df.Year >= 2015]['Engine HP'].isnull().sum()

51

##### Question 5.) 
- Calculate the average "Engine HP" in the dataset.
- Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
- Now, calcualte the average of "Engine HP" again.
- Has it changed?
- Round both means before answering this questions. You can use the round function for that:

**print(round(mean_hp_before))
print(round(mean_hp_after))**

In [16]:
mean_hp_before = df["Engine HP"].mean()
mean_hp_before

249.38607007176023

In [29]:
round(mean_hp_before)

249

In [25]:
df["Engine HP"] = df["Engine HP"].fillna(249.38)

In [27]:
mean_hp_after = df["Engine HP"].mean()
mean_hp_after

249.38603491690392

In [30]:
round(mean_hp_after)

249

##### Question 6.) 
- Select all the "Rolls-Royce" cars from the dataset.
- Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
- Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Invert XTX.
- What's the sum of all the elements of the result?

**Hint: if the result is negative, re-read the task one more time**

In [39]:
X = np.array(df[df.Make == "Rolls-Royce"][["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates())
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [41]:
XTX = X.T.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [46]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [47]:
XTX_inv.sum()

0.032212320677486195

##### Question 7.) 
- Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the value of the first element of w?.

**Note: You just implemented linear regression. We'll talk about it in the next lesson.**

In [48]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [69]:
w = y.dot(X.dot(XTX_inv))
w

array([ 0.19989598, 31.02612262, 31.65378877])